name: Daily Run

on:
  # workflow_dispatch:
  schedule:
    - cron: "25 3 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      OUTLOOK_EMAIL: ${{ vars.OUTLOOK_EMAIL }}
      OUTLOOK_PASSWORD: ${{ secrets.OUTLOOK_PASSWORD }}
      TO_EMAIL: ${{ vars.TO_EMAIL }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run your script
      run: python scrapper.py
